config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :readers

  resources :authors

  resources :books

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :subscriptions
  has_many :readers, :through => :subscriptions
end

app/models/reader.rb
class Reader < ActiveRecord::Base
  has_many :subscriptions
  has_many :books, :through => :subscriptions
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :reader
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where("title like ? or introduction like ?",
                        "%#{params[:query_text]}%", "%#{params[:query_text]}%")
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.update(params[:book])
      reader_ids = params[:reader_ids]
      Subscription.where('book_id = ? ', @book.id ).delete_all
      reader_ids.each do |reader_id|
        Subscription.create :book_id => @book.id, :reader_id => reader_id
      end

      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :public_at, :introduction)
    end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  before_action :set_reader, only: [:show, :edit, :update, :destroy]

  # GET /readers
  # GET /readers.json
  def index
    @readers = Reader.all
  end

  # GET /readers/1
  # GET /readers/1.json
  def show
  end

  # GET /readers/new
  def new
    @reader = Reader.new
  end

  # GET /readers/1/edit
  def edit
  end

  # POST /readers
  # POST /readers.json
  def create
    @reader = Reader.new(reader_params)

    respond_to do |format|
      if @reader.save
        format.html { redirect_to @reader, notice: 'Reader was successfully created.' }
        format.json { render :show, status: :created, location: @reader }
      else
        format.html { render :new }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readers/1
  # PATCH/PUT /readers/1.json
  def update
    respond_to do |format|
      if @reader.update(reader_params)
        format.html { redirect_to @reader, notice: 'Reader was successfully updated.' }
        format.json { render :show, status: :ok, location: @reader }
      else
        format.html { render :edit }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readers/1
  # DELETE /readers/1.json
  def destroy
    @reader.destroy
    respond_to do |format|
      format.html { redirect_to readers_url, notice: 'Reader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reader
      @reader = Reader.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reader_params
      params.require(:reader).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def say_hi name
    "hi, #{name}"
  end
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<h3> 出版的书籍</h3>

<% @author.books.each do |book| %>
  <%= link_to book.title , book_path(:id => book.id) %> <br/>
  <%# link_to book.title , book %>
<% end %>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>

    标题:<br>
    <%= f.text_field :title %> <br/><br/>
    出版时间:<br>
    <%= f.text_field :public_at %><br/><br/>
    介绍:<br>
    <%= f.text_area :introduction %><br/><br/>

    读者: <br/>
    <%= select_tag :reader_ids, options_from_collection_for_select(Reader.all, :id, :name), :multiple => true %>

    <br/><br/>

    <%= f.submit %><br/>
<% end %>

app/views/books/edit.html.erb
<h1>编辑书籍</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>书籍列表</h1>


<%= form_tag '/books', :method => 'get' do %>
  <%= text_field_tag 'query_text', params[:query_text] %>
  <%= submit_tag '查询' %>
<% end %>
<br/>

<table style='border: 1px solid black'>
  <thead>
    <tr>
      <th>标题</th>
      <th>作者</th>
      <th>发表时间</th>
      <th>介绍</th>
      <th>借阅过的人</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author.name %></td>
        <td><%= book.public_at %></td>
        <td><%= book.introduction %></td>
        <td>
          <% book.readers.each do |reader| %>
            <%= reader.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新建', new_book_path %>

app/views/books/new.html.erb
<h1>新建书籍</h1>

<%= say_hi "李磊" %>
<%= render 'form' %>

<%= link_to '返回', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Public at:</strong>
  <%= @book.public_at %>
</p>

<p>
  <strong>Introduction:</strong>
  <%= @book.introduction %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/readers/_form.html.erb
<%= form_for(@reader) do |f| %>
  <% if @reader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reader.errors.count, "error") %> prohibited this reader from being saved:</h2>

      <ul>
      <% @reader.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/readers/edit.html.erb
<h1>Editing reader</h1>

<%= render 'form' %>

<%= link_to 'Show', @reader %> |
<%= link_to 'Back', readers_path %>

app/views/readers/index.html.erb
<h1>读者列表</h1>

<p><%= say_hi "韩梅梅" %></p>
<table style='border: 1px solid black; width: 600px'>
  <thead>
    <tr>
      <th>名称</th>
      <th>借阅过的书</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @readers.each do |reader| %>
      <tr>
        <td><%= reader.name %></td>
        <td>

          <% reader.books.each { |book| %>
            <%= book.title %>,
          <% } %>
        </td>
        <td><%= link_to 'Show', reader %></td>
        <td><%= link_to 'Edit', edit_reader_path(reader) %></td>
        <td><%= link_to 'Destroy', reader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reader', new_reader_path %>

app/views/readers/new.html.erb
<h1>New reader</h1>

<%= render 'form' %>

<%= link_to 'Back', readers_path %>

app/views/readers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reader.name %>
</p>

<%= link_to 'Edit', edit_reader_path(@reader) %> |
<%= link_to 'Back', readers_path %>